-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 11:06:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controldbcopia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controldbcopia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controldbcopia` DEFAULT CHARACTER SET utf8 ;
USE `controldbcopia` ;
-- -----------------------------------------------------
-- Table `controldbcopia`.`documents` X
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typology` INT NOT NULL,
  `process` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` LONGTEXT NULL,
  `version` INT NULL,
  `last_revision` TIMESTAMP NULL,
  `comments` LONGTEXT NULL,
  `link` LONGTEXT NULL,
  `status` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Documentoscol1_UNIQUE` (`version` ASC) ,
  UNIQUE INDEX `CODIGO_UNIQUE` (`code` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`changes` X
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`changes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NULL,
  `code` VARCHAR(45) NULL,
  `new_version` INT NULL,
  `reason` LONGTEXT NULL,
  `aproved_by` VARCHAR(100) NULL,
  `claimant` VARCHAR(100) NULL,
  `details` LONGTEXT NULL,
  `status` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `documents_id` INT NULL,
  PRIMARY KEY (`id`, `documents_id`),
  INDEX `fk_changes_documents1_idx` (`documents_id` ASC) ,
  CONSTRAINT `fk_changes_documents1`
    FOREIGN KEY (`documents_id`)
    REFERENCES `controldbcopia`.`documents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`params` X
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`params` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paramtype_id` INT UNSIGNED NULL,
  `param_foreign` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `status` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `paramtype_id_UNIQUE` (`paramtype_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`param_types` X
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`param_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(205) NULL,
  `range_min` INT(10) NULL,
  `range_max` INT(10) NULL,
  `status` VARCHAR(45) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`storages` X
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`storages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `document_name` MEDIUMTEXT NULL,
  `responsible` VARCHAR(100) NULL,
  `saved_in` VARCHAR(200) NULL,
  `saved_format` VARCHAR(200) NULL,
  `actived_saved` VARCHAR(45) NULL,
  `inactived_saved` VARCHAR(45) NULL,
  `last_move` INT NULL,
  `status` INT NULL,
  `external` INT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `documents_id` INT NULL,
  PRIMARY KEY (`id`, `documents_id`),
  UNIQUE INDEX `Codigo_UNIQUE` (`code` ASC) ,
  INDEX `fk_storages_documents1_idx` (`documents_id` ASC) ,
  CONSTRAINT `fk_storages_documents1`
    FOREIGN KEY (`documents_id`)
    REFERENCES `controldbcopia`.`documents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`users` X
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` LONGTEXT NULL,
  `emaill` VARCHAR(500) NOT NULL,
  `status` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `emaill_UNIQUE` (`emaill` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`audit_programs` X
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`audit_programs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `objetive` LONGTEXT NULL,
  `scope` LONGTEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`processes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`processes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`audit_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`audit_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `controldbcopia`.`audit_program_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`audit_program_fields` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `type` INT UNSIGNED NULL,
  `place` INT UNSIGNED NULL,
  `to_audit` VARCHAR(500) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `processes_id` INT NOT NULL,
  `audit_programs_id` INT NOT NULL,
  `audit_plan_id` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`, `processes_id`, `audit_programs_id`, `audit_plan_id`),
  INDEX `fk_process_audit_programs_procesos1_idx` (`processes_id` ASC) ,
  INDEX `fk_audit_program_fields_audit_programs1_idx` (`audit_programs_id` ASC) ,
  INDEX `fk_audit_program_fields_audit_plan1_idx` (`audit_plan_id` ASC) ,
  CONSTRAINT `fk_process_audit_programs_procesos1`
    FOREIGN KEY (`processes_id`)
    REFERENCES `controldbcopia`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_program_fields_audit_programs1`
    FOREIGN KEY (`audit_programs_id`)
    REFERENCES `controldbcopia`.`audit_programs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_program_fields_audit_plan1`
    FOREIGN KEY (`audit_plan_id`)
    REFERENCES `controldbcopia`.`audit_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`inspectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`inspectors` (
  `id` INT NOT NULL,
  `job` VARCHAR(45) NULL,
  `enroll_date` DATE NULL,
  `full_name` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`files` (
  `id` INT NOT NULL,
  `file_name` LONGTEXT NOT NULL,
  `file_type` MEDIUMTEXT NULL,
  `document` VARCHAR(11) NULL,
  `original_name` LONGTEXT NOT NULL,
  `status` INT NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP() ,
  `documents_id` INT NULL,
  `inspectors_id` INT NULL,
  PRIMARY KEY (`id`, `documents_id`, `inspectors_id`),
  INDEX `fk_files_documents1_idx` (`documents_id` ASC) ,
  INDEX `fk_files_inspectors1_idx` (`inspectors_id` ASC) ,
  CONSTRAINT `fk_files_documents1`
    FOREIGN KEY (`documents_id`)
    REFERENCES `controldbcopia`.`documents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_inspectors1`
    FOREIGN KEY (`inspectors_id`)
    REFERENCES `controldbcopia`.`inspectors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`check_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`check_lists` (
  `id` INT NOT NULL,
  `audit_plan` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ,
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `status` INT NULL,
  `files_id` INT NOT NULL,
  PRIMARY KEY (`id`, `files_id`),
  INDEX `fk_check_list_files1_idx` (`files_id` ASC) ,
  CONSTRAINT `fk_check_list_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `controldbcopia`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`audit_plan_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`audit_plan_fields` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `init_time` TIME NULL,
  `end_time` TIME NULL,
  `place` INT UNSIGNED NULL,
  `audit_plan_id` INT NOT NULL,
  `to_audit` VARCHAR(200) NULL,
  `resources` MEDIUMTEXT NULL,
  `digital_info` MEDIUMTEXT NULL,
  `procesess_id` INT NOT NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `check_list_id` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`, `audit_plan_id`, `procesess_id`, `check_list_id`),
  INDEX `fk_proceso_plan_audit_plan1_idx` (`audit_plan_id` ASC) ,
  INDEX `fk_proceso_plan_procesos1_idx` (`procesess_id` ASC) ,
  INDEX `fk_audit_plan_fields_check_list1_idx` (`check_list_id` ASC) ,
  CONSTRAINT `fk_proceso_plan_audit_plan1`
    FOREIGN KEY (`audit_plan_id`)
    REFERENCES `controldbcopia`.`audit_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proceso_plan_procesos1`
    FOREIGN KEY (`procesess_id`)
    REFERENCES `controldbcopia`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_plan_fields_check_list1`
    FOREIGN KEY (`check_list_id`)
    REFERENCES `controldbcopia`.`check_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`moments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`moments` (
  `id` INT NOT NULL,
  `init_time` TIME NULL,
  `end_time` TIME NULL,
  `moment_type` INT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `audit_plan_id` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`, `audit_plan_id`),
  INDEX `fk_moments_audit_plan1_idx` (`audit_plan_id` ASC) ,
  CONSTRAINT `fk_moments_audit_plan1`
    FOREIGN KEY (`audit_plan_id`)
    REFERENCES `controldbcopia`.`audit_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`inspectors_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`inspectors_roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `initiales` VARCHAR(45) NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`audit_plan_has_inspectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`audit_plan_has_inspectors` (
  `audit_plan_idaudit_plan` INT NOT NULL,
  `inspectors_idinspectors` INT NOT NULL,
  `inspectors_roles_id` INT NOT NULL,
  PRIMARY KEY (`audit_plan_idaudit_plan`, `inspectors_idinspectors`, `inspectors_roles_id`),
  INDEX `fk_audit_plan_has_inspectors_inspectors1_idx` (`inspectors_idinspectors` ASC) ,
  INDEX `fk_audit_plan_has_inspectors_audit_plan1_idx` (`audit_plan_idaudit_plan` ASC) ,
  INDEX `fk_audit_plan_has_inspectors_inspectors_roles1_idx` (`inspectors_roles_id` ASC) ,
  CONSTRAINT `fk_audit_plan_has_inspectors_audit_plan1`
    FOREIGN KEY (`audit_plan_idaudit_plan`)
    REFERENCES `controldbcopia`.`audit_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_plan_has_inspectors_inspectors1`
    FOREIGN KEY (`inspectors_idinspectors`)
    REFERENCES `controldbcopia`.`inspectors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_plan_has_inspectors_inspectors_roles1`
    FOREIGN KEY (`inspectors_roles_id`)
    REFERENCES `controldbcopia`.`inspectors_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`requirements` (
  `id` INT NOT NULL  AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `article` VARCHAR(45) NULL,
  `iso_9001` VARCHAR(45) NULL,
  `iso_45001` VARCHAR(45) NULL,
  `decreto_1072` VARCHAR(45) NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `processes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `processes_id`),
  INDEX `fk_requirements_processes1_idx` (`processes_id` ASC) ,
  CONSTRAINT `fk_requirements_processes1`
    FOREIGN KEY (`processes_id`)
    REFERENCES `controldbcopia`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`emergency_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`emergency_plans` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`risks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`risks` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `emergency_plan_id` INT NOT NULL,
  `audit_plan_id` INT NOT NULL,
  PRIMARY KEY (`id`, `emergency_plan_id`, `audit_plan_id`),
  INDEX `fk_riesgos_plan_contingencia1_idx` (`emergency_plan_id` ASC) ,
  INDEX `fk_risks_audit_plan1_idx` (`audit_plan_id` ASC) ,
  CONSTRAINT `fk_riesgos_plan_contingencia1`
    FOREIGN KEY (`emergency_plan_id`)
    REFERENCES `controldbcopia`.`emergency_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_risks_audit_plan1`
    FOREIGN KEY (`audit_plan_id`)
    REFERENCES `controldbcopia`.`audit_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`final_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`final_reports` (
  `id` INT NOT NULL,
  `filled_objective` TINYINT NULL,
  `presented_risk` LONGTEXT NULL,
  `others` LONGTEXT NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `conclusions` LONGTEXT NULL,
  `files_id` INT NOT NULL,
  `status` INT NULL,
  `action_plan_closeDate` DATE NULL,
  `audit_plan` INT NULL,
  PRIMARY KEY (`id`, `files_id`),
  INDEX `fk_final_report_files1_idx` (`files_id` ASC) ,
  CONSTRAINT `fk_final_report_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `controldbcopia`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`findings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`findings` (
  `id` INT NOT NULL,
  `strength` MEDIUMTEXT NULL,
  `weakness` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `sign` VARCHAR(45) NULL,
  `get_better` VARCHAR(45) NULL,
  `files_id` INT NOT NULL,
  `final_report_id` INT NOT NULL,
  `audit_plan` INT NULL,
  PRIMARY KEY (`id`, `files_id`, `final_report_id`),
  INDEX `fk_findings_files1_idx` (`files_id` ASC) ,
  INDEX `fk_findings_final_report1_idx` (`final_report_id` ASC) ,
  CONSTRAINT `fk_findings_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `controldbcopia`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_findings_final_report1`
    FOREIGN KEY (`final_report_id`)
    REFERENCES `controldbcopia`.`final_reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`check_list_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`check_list_fields` (
  `id` INT NOT NULL,
  `question` LONGTEXT NULL,
  `filled` TINYINT NULL,
  `not_filled` TINYINT NULL,
  `get_better` TINYINT NULL,
  `observations` LONGTEXT NULL,
  `status` INT NULL,
  `iso_9001` LONGTEXT NULL,
  `decreto_1072` LONGTEXT NULL,
  `iso_45001` LONGTEXT NULL,
  `findings_id` INT NOT NULL,
  `check_list_id` INT NOT NULL,
  `audit_plan` INT NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP() ,
  PRIMARY KEY (`id`, `findings_id`, `check_list_id`),
  INDEX `fk_campos_lista_chequeo_hallazgos1_idx` (`findings_id` ASC) ,
  INDEX `fk_campos_lista_chequeo_lista_chequeo1_idx` (`check_list_id` ASC) ,
  CONSTRAINT `fk_campos_lista_chequeo_hallazgos1`
    FOREIGN KEY (`findings_id`)
    REFERENCES `controldbcopia`.`findings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campos_lista_chequeo_lista_chequeo1`
    FOREIGN KEY (`check_list_id`)
    REFERENCES `controldbcopia`.`check_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`action_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`action_plans` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`finding_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`finding_fields` (
  `id` INT NOT NULL,
  `requirement` VARCHAR(45) NULL,
  `no_comformity` VARCHAR(45) NULL,
  `get_better` VARCHAR(45) NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `findings_id` INT NOT NULL,
  `action_plan_id` INT NOT NULL,
  PRIMARY KEY (`id`, `findings_id`, `action_plan_id`),
  INDEX `fk_campos_hallazgos_hallazgos1_idx` (`findings_id` ASC) ,
  INDEX `fk_campos_hallazgos_plan_accion1_idx` (`action_plan_id` ASC) ,
  CONSTRAINT `fk_campos_hallazgos_hallazgos1`
    FOREIGN KEY (`findings_id`)
    REFERENCES `controldbcopia`.`findings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campos_hallazgos_plan_accion1`
    FOREIGN KEY (`action_plan_id`)
    REFERENCES `controldbcopia`.`action_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`evaluations` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `fullfil_plan` VARCHAR(45) NULL,
  `fullfil_date` VARCHAR(45) NULL,
  `inform` MEDIUMTEXT NULL,
  `conclusion` VARCHAR(45) NULL,
  `good_interaction` VARCHAR(45) NULL,
  `total_score` VARCHAR(45) NULL,
  `final_score` VARCHAR(45) NULL,
  `inspectors_id` INT NOT NULL,
  `files_id` INT NOT NULL,
  `created_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`, `inspectors_id`, `files_id`),
  INDEX `fk_evaluacion_desempeño_inspectors1_idx` (`inspectors_id` ASC) ,
  INDEX `fk_evaluations_files1_idx` (`files_id` ASC) ,
  CONSTRAINT `fk_evaluacion_desempeño_inspectors1`
    FOREIGN KEY (`inspectors_id`)
    REFERENCES `controldbcopia`.`inspectors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluations_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `controldbcopia`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldbcopia`.`inspectors_has_audit_plan_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldbcopia`.`inspectors_has_audit_plan_fields` (
  `inspectors_id` INT NOT NULL,
  `audit_plan_fields_id` INT NOT NULL,
  `audit_plan_fields_audit_plan_id` INT NOT NULL,
  `audit_plan_fields_procesess_id` INT NOT NULL,
  PRIMARY KEY (`inspectors_id`, `audit_plan_fields_id`, `audit_plan_fields_audit_plan_id`, `audit_plan_fields_procesess_id`),
  INDEX `fk_inspectors_has_audit_plan_fields_audit_plan_fields1_idx` (`audit_plan_fields_id` ASC, `audit_plan_fields_audit_plan_id` ASC, `audit_plan_fields_procesess_id` ASC) ,
  INDEX `fk_inspectors_has_audit_plan_fields_inspectors1_idx` (`inspectors_id` ASC) ,
  CONSTRAINT `fk_inspectors_has_audit_plan_fields_inspectors1`
    FOREIGN KEY (`inspectors_id`)
    REFERENCES `controldbcopia`.`inspectors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inspectors_has_audit_plan_fields_audit_plan_fields1`
    FOREIGN KEY (`audit_plan_fields_id` , `audit_plan_fields_audit_plan_id` , `audit_plan_fields_procesess_id`)
    REFERENCES `controldbcopia`.`audit_plan_fields` (`id` , `audit_plan_id` , `procesess_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
